name: Plugin CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:

    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: build
        uses: gradle/gradle-build-action@v2

      - name: test
        run:  mvn -ntp clean test
